/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Main */

#ifndef _Included_com_Main
#define _Included_com_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Main
 * Method:    getSize
 * Signature: (Lcom/User;)I
 */
JNIEXPORT jint JNICALL Java_com_Main_getSize
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
